# Generated by Django 3.2.9 on 2021-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211218_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='miles',
        ),
        migrations.AddField(
            model_name='car',
            name='mot',
            field=models.CharField(blank=True, choices=[('12', '12'), ('11', '11'), ('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('No MOT', 'No MOT')], max_length=20),
        ),
    ]
