# Generated by Django 3.2.9 on 2021-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211218_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Bi Fuel', 'Bi Fuel'), ('Diesel', 'Diesel'), ('Diesel Hybrid', 'Diesel Hybrid'), ('Diesel Plug-in Hybrid', 'Diesel Plug-in Hybrid'), ('Electric', 'Electric'), ('Hydrogen', 'Hydrogen'), ('Natural Gas', 'Natural Gas'), ('Petrol', 'Petrol'), ('Petrol Hybrid', 'Petrol Hybrid'), ('Petrol Plug-in Hybrid', 'Petrol Plug-in Hybrid')], max_length=50),
        ),
    ]
