# Generated by Django 3.2.9 on 2021-12-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_fuel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='colour',
        ),
    ]
