# Generated by Django 3.2.9 on 2021-12-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_color_car_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mot',
            field=models.CharField(blank=True, choices=[('12', '12 months'), ('11', '11 months'), ('10', '10 months'), ('9', '9 months'), ('8', '8 months'), ('7', '7 months'), ('6', '6 months'), ('5', '5 months'), ('4', '4 months'), ('3', '3 months'), ('2', '2 months'), ('1', '1 month'), ('No MOT', 'No MOT')], max_length=20),
        ),
    ]
